services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  business-ingestor:
    container_name: business_ingest_service
    build:
      context: .
      dockerfile: ./infra/ingestion/business_dept/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5432
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
  customer-ingestor:
    container_name: customer_ingest_service
    build:
      context: .
      dockerfile: ./infra/ingestion/customer_dept/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5432
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
  enterprise-ingestor:
    container_name: enterprise_ingest_service
    build:
      context: .
      dockerfile: ./infra/ingestion/enterprise_dept/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5432
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
  marketing-ingestor:
    container_name: marketing_ingest_service
    build:
      context: .
      dockerfile: ./infra/ingestion/marketing_dept/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5432
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
  operations-ingestor:
    container_name: operations_ingest_service
    build:
      context: .
      dockerfile: ./infra/ingestion/operations_dept/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: 5432
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: