services:
  warehouse_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shopzada
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    build:
      context: .
    depends_on:
      - postgres
    entrypoint: 
      - bash
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --firstname Air \
          --lastname Flow \
          --role Admin \
          --email admin@example.com \
          --password admin
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dags:/opt/airflow/data

  airflow-webserver:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow 
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8070:8080"
    command: webserver
  airflow-scheduler:
    build:
      context: .
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    command: scheduler

  ingestor-service:
    image: ShopZada/ingestor-service:latest
    build:
      context: .
      dockerfile: ./infra/ingestion/Dockerfile
    environment:
      DB_HOST: warehouse_db
      DB_USER: admin
      DB_PASSWORD: mypassword
      DB_NAME: shopzada
      DB_PORT: 5432
    volumes:
      - ./data:/app/data
    depends_on:
      - warehouse_db

  to_dw-service:
    image: ShopZada/to_dw-service:latest
    build:
      context: .
      dockerfile: ./infra/transform_to_dw/Dockerfile
    environment:
      DB_HOST: warehouse_db
      DB_USER: admin
      DB_PASSWORD: mypassword
      DB_NAME: shopzada
      DB_PORT: 5432
    volumes:
      - ./data:/app/data
    depends_on:
      - warehouse_db
volumes:
  pgdata: