services:
  warehouse_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shopzada
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d shopzada"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow_metatada-db:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  airflow-init:
    image: apache/airflow:2.9.1
    depends_on:
      - airflow_metatada-db
    entrypoint: 
      - bash
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin \
          --firstname Air \
          --lastname Flow \
          --role Admin \
          --email admin@example.com \
          --password admin
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_metatada-db:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dags:/opt/airflow/data

  airflow-webserver:
    image: apache/airflow:2.9.1
    depends_on:
      - airflow_metatada-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-docker"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_metatada-db:5432/airflow 
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      PROJECT_HOME: ${PROJECT_HOME}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8070:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_metatada-db:5432/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-docker"
      PROJECT_HOME: ${PROJECT_HOME}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler

  ingestor-service:
    image: ShopZada/ingestor-service:latest
    build:
      context: .
      dockerfile: ./infra/ingestion/Dockerfile
    environment:
      DB_HOST: warehouse_db
      DB_USER: admin
      DB_PASSWORD: mypassword
      DB_NAME: shopzada
      DB_PORT: 5432
    volumes:
      - ./data:/app/data
    depends_on:
      - warehouse_db

  to_dw-service:
    image: ShopZada/to_dw-service:latest
    build:
      context: .
      dockerfile: ./infra/transform_to_dw/Dockerfile
    environment:
      DB_HOST: warehouse_db
      DB_USER: admin
      DB_PASSWORD: mypassword
      DB_NAME: shopzada
      DB_PORT: 5432
    volumes:
      - ./data:/app/data
    depends_on:
      - warehouse_db

volumes:
  pgdata:
  postgres-db-volume: